package server.common;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

class ResourceManagerTest {
    private ResourceManager rm;

    @BeforeEach
    void setUp() {
        rm = new ResourceManager("TestRM");
    }

    @Test
    void testGetName() {
        assertEquals("TestRM", rm.getName());
    }

    // Flight Operations Tests
    @Test
    void testAddNewFlight() {
        assertTrue(rm.addFlight(123, 150, 200));

        assertEquals(150, rm.queryFlight(123));
        assertEquals(200, rm.queryFlightPrice(123));
    }

    @Test
    void testAddFlightToExisting() {
        rm.addFlight(123, 150, 200);
        rm.addFlight(123, 50, 250); // Add more seats, update price

        assertEquals(200, rm.queryFlight(123)); // 150 + 50
        assertEquals(250, rm.queryFlightPrice(123)); // Updated price
    }

    @Test
    void testAddFlightToExistingZeroPrice() {
        rm.addFlight(123, 150, 200);
        rm.addFlight(123, 50, 0); // Zero price shouldn't update

        assertEquals(200, rm.queryFlight(123));
        assertEquals(200, rm.queryFlightPrice(123)); // Price unchanged
    }

    @Test
    void testQueryNonExistentFlight() {
        assertEquals(0, rm.queryFlight(999));
        assertEquals(0, rm.queryFlightPrice(999));
    }

    @Test
    void testDeleteFlight() {
        rm.addFlight(123, 150, 200);
        assertTrue(rm.deleteFlight(123));

        assertEquals(0, rm.queryFlight(123));
    }

    @Test
    void testDeleteNonExistentFlight() {
        assertFalse(rm.deleteFlight(999));
    }

    @Test
    void testDeleteFlightWithReservations() {
        rm.addFlight(123, 150, 200);
        rm.newCustomer(1);
        rm.reserveFlight(1, 123);

        assertFalse(rm.deleteFlight(123)); // Should fail due to reservations
        assertEquals(149, rm.queryFlight(123)); // Still available but one reserved
    }

    // Car Operations Tests
    @Test
    void testAddNewCars() {
        assertTrue(rm.addCars("Montreal", 10, 50));

        assertEquals(10, rm.queryCars("Montreal"));
        assertEquals(50, rm.queryCarsPrice("Montreal"));
    }

    @Test
    void testAddCarsToExisting() {
        rm.addCars("Montreal", 10, 50);
        rm.addCars("Montreal", 5, 60);

        assertEquals(15, rm.queryCars("Montreal"));
        assertEquals(60, rm.queryCarsPrice("Montreal"));
    }

    @Test
    void testQueryNonExistentCars() {
        assertEquals(0, rm.queryCars("Toronto"));
        assertEquals(0, rm.queryCarsPrice("Toronto"));
    }

    @Test
    void testDeleteCars() {
        rm.addCars("Montreal", 10, 50);
        assertTrue(rm.deleteCars("Montreal"));

        assertEquals(0, rm.queryCars("Montreal"));
    }

    @Test
    void testDeleteNonExistentCars() {
        assertFalse(rm.deleteCars("Toronto"));
    }

    // Room Operations Tests
    @Test
    void testAddNewRooms() {
        assertTrue(rm.addRooms("Toronto", 25, 80));

        assertEquals(25, rm.queryRooms("Toronto"));
        assertEquals(80, rm.queryRoomsPrice("Toronto"));
    }

    @Test
    void testAddRoomsToExisting() {
        rm.addRooms("Toronto", 25, 80);
        rm.addRooms("Toronto", 15, 90);

        assertEquals(40, rm.queryRooms("Toronto"));
        assertEquals(90, rm.queryRoomsPrice("Toronto"));
    }

    @Test
    void testQueryNonExistentRooms() {
        assertEquals(0, rm.queryRooms("Vancouver"));
        assertEquals(0, rm.queryRoomsPrice("Vancouver"));
    }

    @Test
    void testDeleteRooms() {
        rm.addRooms("Toronto", 25, 80);
        assertTrue(rm.deleteRooms("Toronto"));

        assertEquals(0, rm.queryRooms("Toronto"));
    }

    @Test
    void testDeleteNonExistentRooms() {
        assertFalse(rm.deleteRooms("Vancouver"));
    }

    // Customer Operations Tests
    @Test
    void testNewCustomerAutoGenerated() {
        Integer customerId = rm.newCustomer();

        assertNotNull(customerId);
        assertTrue(customerId > 0);

        // Customer should exist and have empty bill
        String bill = rm.queryCustomerInfo(customerId);
        assertTrue(bill.contains("Bill for customer " + customerId));
    }

    @Test
    void testNewCustomerWithId() {
        assertTrue(rm.newCustomer(123));

        String bill = rm.queryCustomerInfo(123);
        assertTrue(bill.contains("Bill for customer 123"));
    }

    @Test
    void testNewCustomerDuplicateId() {
        rm.newCustomer(123);
        assertFalse(rm.newCustomer(123)); // Should fail for duplicate
    }

    @Test
    void testQueryNonExistentCustomer() {
        String bill = rm.queryCustomerInfo(999);
        assertEquals("", bill); // Empty string for non-existent customer
    }

    @Test
    void testDeleteCustomer() {
        rm.newCustomer(123);
        assertTrue(rm.deleteCustomer(123));

        String bill = rm.queryCustomerInfo(123);
        assertEquals("", bill); // Customer should no longer exist
    }

    @Test
    void testDeleteNonExistentCustomer() {
        assertFalse(rm.deleteCustomer(999));
    }

    @Test
    void testDeleteCustomerWithReservations() {
        rm.addFlight(123, 150, 200);
        rm.addCars("Montreal", 10, 50);
        rm.newCustomer(1);

        rm.reserveFlight(1, 123);
        rm.reserveCar(1, "Montreal");

        // Before deletion
        assertEquals(149, rm.queryFlight(123));
        assertEquals(9, rm.queryCars("Montreal"));

        assertTrue(rm.deleteCustomer(1));

        // After deletion - items should be returned to inventory
        assertEquals(150, rm.queryFlight(123));
        assertEquals(10, rm.queryCars("Montreal"));
    }

    // Reservation Tests
    @Test
    void testReserveFlight() {
        rm.addFlight(123, 150, 200);
        rm.newCustomer(1);

        assertTrue(rm.reserveFlight(1, 123));

        assertEquals(149, rm.queryFlight(123)); // One less available

        String bill = rm.queryCustomerInfo(1);
        assertTrue(bill.contains("1 flight-123 $200"));
    }

    @Test
    void testReserveFlightNonExistentCustomer() {
        rm.addFlight(123, 150, 200);
        assertFalse(rm.reserveFlight(999, 123));
    }

    @Test
    void testReserveFlightNonExistentFlight() {
        rm.newCustomer(1);
        assertFalse(rm.reserveFlight(1, 999));
    }

    @Test
    void testReserveFlightOutOfStock() {
        rm.addFlight(123, 0, 200); // No seats available
        rm.newCustomer(1);

        assertFalse(rm.reserveFlight(1, 123));
    }

    @Test
    void testReserveFlightMultiple() {
        rm.addFlight(123, 150, 200);
        rm.newCustomer(1);

        assertTrue(rm.reserveFlight(1, 123));
        assertTrue(rm.reserveFlight(1, 123));

        assertEquals(148, rm.queryFlight(123)); // Two less available

        String bill = rm.queryCustomerInfo(1);
        assertTrue(bill.contains("2 flight-123 $200"));
    }

    @Test
    void testReserveCar() {
        rm.addCars("Montreal", 10, 50);
        rm.newCustomer(1);

        assertTrue(rm.reserveCar(1, "Montreal"));

        assertEquals(9, rm.queryCars("Montreal"));

        String bill = rm.queryCustomerInfo(1);
        assertTrue(bill.contains("1 car-montreal $50"));
    }

    @Test
    void testReserveRoom() {
        rm.addRooms("Toronto", 25, 80);
        rm.newCustomer(1);

        assertTrue(rm.reserveRoom(1, "Toronto"));

        assertEquals(24, rm.queryRooms("Toronto"));

        String bill = rm.queryCustomerInfo(1);
        assertTrue(bill.contains("1 room-toronto $80"));
    }

    // Bundle Tests
    @Test
    void testBundleNotImplemented() {
        // Bundle is not implemented in base ResourceManager
        assertFalse(rm.bundle(1, null, null, false, false));
    }

    // Integration Tests
    @Test
    void testCompleteScenario() {
        // Add inventory
        rm.addFlight(123, 2, 200);
        rm.addCars("Montreal", 3, 50);
        rm.addRooms("Montreal", 1, 80);

        // Create customers
        rm.newCustomer(1);
        rm.newCustomer(2);

        // Make reservations
        assertTrue(rm.reserveFlight(1, 123));
        assertTrue(rm.reserveFlight(2, 123));
        assertTrue(rm.reserveCar(1, "Montreal"));
        assertTrue(rm.reserveRoom(1, "Montreal"));

        // Check inventory
        assertEquals(0, rm.queryFlight(123)); // Both seats taken
        assertEquals(2, rm.queryCars("Montreal")); // One car taken
        assertEquals(0, rm.queryRooms("Montreal")); // One room taken

        // Check customer bills
        String bill1 = rm.queryCustomerInfo(1);
        assertTrue(bill1.contains("1 flight-123 $200"));
        assertTrue(bill1.contains("1 car-montreal $50"));
        assertTrue(bill1.contains("1 room-montreal $80"));

        String bill2 = rm.queryCustomerInfo(2);
        assertTrue(bill2.contains("1 flight-123 $200"));
        assertFalse(bill2.contains("car-montreal"));
        assertFalse(bill2.contains("room-montreal"));
    }

    @Test
    void testPriceUpdateScenario() {
        // Add initial inventory
        rm.addFlight(123, 100, 200);
        rm.addCars("Montreal", 10, 50);

        // Reserve at current prices
        rm.newCustomer(1);
        rm.reserveFlight(1, 123);
        rm.reserveCar(1, "Montreal");

        // Update prices
        rm.addFlight(123, 0, 250); // Price increase, no new seats
        rm.addCars("Montreal", 0, 60); // Price increase, no new cars

        // New customer reserves at new prices
        rm.newCustomer(2);
        rm.reserveFlight(2, 123);
        rm.reserveCar(2, "Montreal");

        // Check bills - should reflect prices at time of reservation
        String bill1 = rm.queryCustomerInfo(1);
        assertTrue(bill1.contains("1 flight-123 $200")); // Old price
        assertTrue(bill1.contains("1 car-montreal $50")); // Old price

        String bill2 = rm.queryCustomerInfo(2);
        assertTrue(bill2.contains("1 flight-123 $250")); // New price
        assertTrue(bill2.contains("1 car-montreal $60")); // New price
    }

    @Test
    void testConcurrencyDataIntegrity() {
        // Test that synchronized blocks protect data integrity
        rm.addFlight(123, 1, 200);
        rm.newCustomer(1);
        rm.newCustomer(2);

        // Both try to reserve the single seat
        boolean result1 = rm.reserveFlight(1, 123);
        boolean result2 = rm.reserveFlight(2, 123);

        // Only one should succeed
        assertTrue(result1 != result2); // Exactly one should be true
        assertEquals(0, rm.queryFlight(123)); // Flight should be fully booked
    }

    @Test
    void testEdgeCasesZeroValues() {
        // Test with zero counts and prices
        assertTrue(rm.addFlight(123, 0, 200));
        assertEquals(0, rm.queryFlight(123));

        assertTrue(rm.addCars("Montreal", 10, 0));
        assertEquals(0, rm.queryCarsPrice("Montreal"));

        rm.newCustomer(0); // Customer ID zero should work
        assertNotEquals("", rm.queryCustomerInfo(0));
    }
}
