build:
    ./gradlew clean build

clean:
    rm -f *.log*
    rm -f *.lck*

run player_num:
    just build && \
    ./comp512st/tiapp/run_tiapp.sh {{player_num}}

kill:
    pkill -f "comp512p2.jar" || true

auto-test:
    just kill && \
    just build && \
    ./comp512st/tests/run_tiapp_auto.sh

deploy:
    just build
    ./scripts/deploy.sh

trim:
    ./scripts/trim_logs.sh

check:
    python3 ./scripts/log_checker.py

run-nuke:
    -kill -9 $(lsof -ti:40122,40222,40322,40422,40522,40622,40722,40822,40922)
    rm -f *.log*
    rm -f *.lck*
    ./gradlew clean build
