build:
    ./gradlew clean build

clean:
    rm -f *.log*
    rm -f *.lck*

run player_num:
    just build && \
    source .env && \
    ./comp512st/tiapp/run_tiapp.sh {{player_num}}

kill:
    pkill -f "comp512p2.jar" || true

auto-test:
    just kill && \
    just build && \
    source .env && \
    ./comp512st/tests/run_tiapp_auto.sh
