# ========== Build ==========

build-all app_type:
    just build-shared
    just build-server {{app_type}}
    just build-client {{app_type}}
    just build-middleware {{app_type}}

build-shared:
    ./gradlew :shared:clean build

build-server server_type:
    ./gradlew :server:clean build -PserverType={{server_type}}

build-client client_type:
    ./gradlew :client:clean build -PclientType={{client_type}}

build-middleware middleware_type:
    ./gradlew :middleware:clean build -PmiddlewareType={{middleware_type}}


# ========== Test ==========

test:
    ./gradlew clean test


# ========== Shutdown ==========

stop-all:
    just stop-client
    just stop-middleware
    just stop-servers
    sleep 2 # give some time for servers to close connections

    just stop-rmiregistry

stop-rmiregistry:
    lsof -ti :1122 | xargs -r kill -TERM

stop-servers:
    pgrep -u $(whoami) -f run-server | grep -v $$ | xargs -r kill -TERM

stop-client:
    pgrep -u $(whoami) -f run-client | grep -v $$ | xargs -r kill -TERM

stop-middleware:
    pgrep -u $(whoami) -f run-middleware | grep -v $$ | xargs -r kill -TERM


# ========== Run ==========

# run all components, ONLY MEANT FOR LOCAL TESTING
# see bash scripts for running system in distributed mode
run-all app_type:
    just stop-all

    if [ "{{app_type}}" = "rmi" ]; then \
        just run-rmiregistry; \
        sleep 3; \
    fi

    tmux kill-session -t a1 2>/dev/null || true
    tmux new-session -d -s a1 \; \
        split-window -h \; \
        split-window -v \; \
        select-pane -t 0 \; \
        split-window -v \; \
        select-layout tiled

    tmux send-keys -t a1:0.1 "just run-server {{app_type}} Flights" C-m
    sleep 3
    tmux send-keys -t a1:0.2 "just run-server {{app_type}} Cars" C-m
    sleep 3
    tmux send-keys -t a1:0.3 "just run-server {{app_type}} Rooms" C-m
    sleep 3
    tmux send-keys -t a1:0.0 "just run-middleware {{app_type}}" C-m
    sleep 3

    just run-client {{app_type}} Middleware

run-rmiregistry: build-shared
    CLASSPATH=shared/build/classes/java/main rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false 1122 &

run-server server_type rm_object:
    ./gradlew :server:installDist -PserverType={{server_type}}
    ./server/build/install/server/bin/server {{rm_object}}

run-client client_type server_name:
    ./gradlew :client:installDist -PclientType={{client_type}}
    ./client/build/install/client/bin/client localhost {{server_name}}

run-middleware middleware_type:
    ./gradlew :middleware:installDist -PmiddlewareType={{middleware_type}}
    ./middleware/build/install/middleware/bin/middleware localhost localhost localhost
