# build all packages
build-all app_type:
    just build-shared
    just build-server {{app_type}}
    just build-client {{app_type}}
    just build-middleware {{app_type}}

# build the shared library
build-shared:
    ./gradlew :shared:clean build

# build the server app
build-server server_type:
    ./gradlew :server:clean build -PserverType={{server_type}}

# build the client app
build-client client_type:
    ./gradlew :client:clean build -PclientType={{client_type}}

# build the middleware app
build-middleware middleware_type:
    ./gradlew :middleware:clean build -PmiddlewareType={{middleware_type}}

# stop all processes (reverse order in which we ran them)
stop-all:
    just stop-client
    just stop-middleware
    just stop-servers
    sleep 2 # give some time for servers to close connections

    just stop-rmiregistry

stop-rmiregistry:
    pgrep -f rmiregistry >/dev/null 2>&1 && pkill -TERM -f rmiregistry || true

stop-servers:
    pgrep -f rmiregistry >/dev/null 2>&1 && pkill -TERM -f run-server || true

stop-client:
    pgrep -f rmiregistry >/dev/null 2>&1 && pkill -TERM -f run-client || true

stop-middleware:
    pgrep -f rmiregistry >/dev/null 2>&1 && pkill -TERM -f middleware || true

# order of commands matter
run-all app_type:
    just stop-all

    just _run-rmi {{app_type}} &
    sleep 3
    
    tmux kill-session -t cars 2>/dev/null || true
    tmux new-session -d -s cars 'just run-server Cars {{app_type}}'
    sleep 3

    tmux kill-session -t rooms 2>/dev/null || true
    tmux new -d -s rooms 'just run-server Rooms {{app_type}}'
    sleep 3

    tmux kill-session -t flights 2>/dev/null || true
    tmux new -d -s flights 'just run-server Flights {{app_type}}'
    sleep 3

    tmux kill-session -t middleware 2>/dev/null || true
    tmux new -d -s middleware 'just run-middleware {{app_type}}'
    sleep 3

    just run-client localhost Middleware {{app_type}}

_run-rmi app_type:
    #!/usr/bin/env bash
    if [ "{{app_type}}" = "rmi" ]; then
        just run-rmiregistry &
    fi

# start the rmi registry
run-rmiregistry: build-shared
    CLASSPATH=shared/build/classes/java/main rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false 1122

# start a server
run-server rm_object server_type: (build-server server_type)
    ./gradlew :server:installDist
    ./server/build/install/server/bin/server {{rm_object}}

# start a client
run-client hostname rm_object client_type: (build-client client_type)
    ./gradlew :client:installDist
    ./client/build/install/client/bin/client {{hostname}} {{rm_object}}

# start a middleware
run-middleware middleware_type: (build-middleware middleware_type)
    ./gradlew :middleware:installDist
    ./middleware/build/install/middleware/bin/middleware
