set dotenv-load

build-all:
    ./gradlew clean build

run-client samples:
    ./gradlew :client:run --args={{samples}}

run-dist:
    ./gradlew :dist:run

zk-cli:
    zkCli -server localhost:2181

clean-zk:
    zkCli -server localhost:2181 <<< "deleteall /dist22"

    zkCli -server localhost:2181 <<< "create /dist22"
    zkCli -server localhost:2181 <<< "create /dist22/workers"
    zkCli -server localhost:2181 <<< "create /dist22/tasks"
