set dotenv-load

build-all:
    ./gradlew clean build

run-client samples:
    ./gradlew :client:run --args={{samples}}

run-dist:
    ./gradlew :dist:run

zk-cli:
    zkCli -server $ZKSERVER

clean-zk:
    zkCli -server $ZKSERVER <<< "deleteall /dist22"

    zkCli -server $ZKSERVER <<< "create /dist22"
    zkCli -server $ZKSERVER <<< "create /dist22/workers"
    zkCli -server $ZKSERVER <<< "create /dist22/tasks"

deploy:
    just build-all

    # client
    scp -r ./client/bin "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/client"
    scp -r ./client/build "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/client"

    # dist
    scp -r ./dist/bin "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/dist"
    scp -r ./dist/build "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/dist"

    # shared
    scp -r ./shared/bin "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/shared"
    scp -r ./shared/build "$MIMI_USER@mimi.cs.mcgill.ca:/home/2023/$MIMI_USER/comp-512/a3/shared"

# following commands are meant for usage on trottier nodes
run-dist-tr:
    . $ZOOBINDIR/zkEnv.sh
    export ZKSERVER
    export GROUP_NUM
    java -cp "$CLASSPATH:dist/bin/main:shared/bin/main:." DistProcess

run-client-tr samples:
    . $ZOOBINDIR/zkEnv.sh
    export ZKSERVER
    export GROUP_NUM
    java -cp "$CLASSPATH:client/bin/main:shared/bin/main:." DistClient {{samples}}
