/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":client"))
    implementation(project(":shared"))
    implementation(project(":server"))

    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("ch.qos.logback:logback-classic:1.5.18")

    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.mockito:mockito-core:5.13.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.13.0")
    testImplementation("org.assertj:assertj-core:3.26.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    getByName("main") {
        java.srcDirs("src/main/java")
    }

    getByName("test") {
        java.srcDirs("src/test/java")
        resources.srcDirs("src/test/resources")
    }
}

application {
    val middlewareType = project.findProperty("middlewareType")?.toString() ?: "rmi"
    mainClass = when (middlewareType.lowercase()) {
        "rmi" -> "middleware.rmi.RMIMiddleware"
        "tcp" -> "middleware.tcp.TCPMiddleware"
        else -> throw GradleException("Invalid middlewareType: $middlewareType. Must be 'rmi' or 'tcp'")
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed", "standard_out", "standard_error")
        showStandardStreams = true
    }
}