/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":shared"))

    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("ch.qos.logback:logback-classic:1.5.18")
    implementation("org.json:json:20240303")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    getByName("main") {
        java.srcDirs("src")
    }
}

application {
    val clientType = project.findProperty("clientType")?.toString() ?: "rmi"
    mainClass = when (clientType.lowercase()) {
        "rmi" -> "client.rmi.RMIClient"
        "tcp" -> "client.tcp.TCPClient"
        else -> throw GradleException("Invalid clientType: $clientType. Must be 'rmi' or 'tcp'")
    }
}