# build all packages
build-all:
    ./gradlew clean build

# build the server app
build-server:
    ./gradlew :server:clean build

# build the client app
build-client:
    ./gradlew :client:clean build

# build the shared library
build-shared:
    ./gradlew :shared:clean build

# start the rmi registry
run-rmi: build-shared
    CLASSPATH=shared/build/classes/java/main rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false 1099 &

# start a server
run-server rmi_object: build-server
    java -cp server/build/classes/java/main:shared/build/classes/java/main server.rmi.RMIResourceManager {{rmi_object}}

# start a client
run-client hostname rmi_object: build-client
    java -cp client/build/classes/java/main:shared/build/classes/java/main client.RMIClient {{hostname}} {{rmi_object}}
